### ISSUE TITLE
https://www.xenial.io/ never loads

### ISSUE THREAD

**Issue by petrechitashvili** [xenial-io/Xenial.Framework#46]
Navigating to https://www.xenial.io loads just the SVG image - the site never loads.

![image](https://user-images.githubusercontent.com/15320885/134168906-a890990a-a8ef-4da3-9acd-87ca09217fa1.png)

**Comment by biohazard999** [comment]
@petrechitashvili Sorry for that long delay: the reason is the store isn't online yet. please visit the [staging site](https://stage.xenial.io) for now.

**Comment by petrechitashvili** [comment]
Got it. 
Thank you @biohazard999 
/close
