### ISSUE TITLE
XenialAdvancedModelEditorActionsViewController - Move actions to the 'Tools' category

### ISSUE THREAD

**Issue by p0utine** [xenial-io/Xenial.Framework#61]
The `OpenViewInModelEditorSimpleAction` and `OpenBOModelInModelEditorSimpleAction` appear in the `Diagnostic` action category. I think they should be moved to the `Tools` action category to match the ones from DX.

![image](https://user-images.githubusercontent.com/87371546/146404881-75640a9f-1250-4885-baeb-d2564be5a21b.png)

**Comment by biohazard999** [comment]
We can remove the whole controller because its already in XAF see #60

**Comment by p0utine** [comment]
Yes. The equivalent to `Edit BOModel` is this out-of-the-box choice item:

![image](https://user-images.githubusercontent.com/87371546/146926436-d9cdd057-79a3-4381-b75d-064c5faa8c67.png)
