### ISSUE TITLE
Add more descriptive NuGet packages tags

### ISSUE THREAD

**Issue by p0utine** [xenial-io/Xenial.Framework#76]
All Xenial packages tags are assigned from `Xenial.Framework\src\Directory.Build.props` which appears to be a copy/paste from Tasty.

`<PackageTags>Xenial, Tasty, Testing, Tasting, UnitTasting, IntegrationTasting, xUnit, NUnit, MSTest, UnitTest, IntegrationTest, BDD, TDD, Jest</PackageTags>`

I think we could remove all the tags related to testing and add at the minimum:
- eXpressApp
- DevExpress
- XAF

For the individual editor packages, a variation of this:
- PropertyEditor
- The platform: Agnostic, Win or Blazor
- Some keyword related to the editor: Badges, WebView, Token,

We could have the base Xenial tags in a MSBuild property and can concat them with specific tags per package if needed.

@biohazard999 What do you think? Any tag I missed?

**Comment by biohazard999** [comment]
Looks good as proposed
